apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    # all the pods that match this label belong to this depoyment
    matchLabels:
      app: mongo
  template:
    metadata:
     # this label used to identify pods that are running this app
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password  
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  # specify what pods the service need to forward the requests to
  selector:
    app: mongo
  ports:
    - protocol: TCP
      # port of the service
      port: 27017
      # the port of the pod, the service will forward the request to this port
      targetPort: 27017
